
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # opcional, Ãºtil pra acessar localmente com um cliente
    restart: always  # opcional, mas bom pra dev

  app:
    image: golang:1.22
    command: ["go", "run", "main.go"]
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=root
      - DB_PORT=5432

volumes:
  pgdata:
